directory: C:\Users\OMMAR\Desktop\Apollo\beets\musiccc
plugins: duplicates filefilter missing random importfeeds badfiles autofix
autofix:
    max_exec_time: 0
    tasks:
        missing_file_checker:
            enabled: yes
        year_fixer:
            enabled: no
        audio_conversion:
            enabled: no
        tag_cleaner:
            enabled: no
        ab_data_fetcher:
            enabled: no
        xtractor:
            enabled: no
        genre_finder:
            enabled: no